version: '2.1'
services:
  tor_proxy_agent:
    build: ./tor_proxy
    command: sh -c "tor"
    container_name: tor_proxy_agent
    ports:
      - "8050:9050"
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build: .
    volumes:
      - .:/var/www
<<<<<<< HEAD
    command: ["python", "scratch_downloader.py"]
=======
    command: ["python", "downloader.py", "--amount", "${AMOUNT}", "--query", "${QUERY}", "--mode", "${MODE}", "--language", "${LANGUAGE}"]
>>>>>>> 965d8604da90a5eb72e7686867143c18ad520666
    container_name: scratch_downloader
    user: root
    volumes:
      - .:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "7000:8000"
    env_file:
      - ./PARAMS
    stdin_open: true
    init: true
    tty: true
    depends_on:
      tor_proxy_agent:
        condition: service_healthy
volumes:
  dbdata: