
"""QUERY_LIST = [
    "film", "tv", "anime", "meme", "cartoon", "hero", "music", "movie", 
    "comedy", "dance", "star", "magic", "rpg", "strategy", "puzzle", "tycoon", 
    "sandbox", "runner", "battle", "shooter", "adventure", "arcade", "platform", 
    "clicker", "maze", "pong", "survival", "space", "minecraft", "zombie", 
    "defense", "speed", "math", "history", "map", "language", "calculator", 
    "cards", "coding", "science", "physics", "spelling", "chemistry", 
    "biology", "logic", "quiz", "drawing", "design", "building", "art", 
    "sketch", "model", "virtual", "house", "robot", "machine", "flight", 
    "car", "city", "farm", "traffic", "poll", "test", "story", "choice", 
    "decision", "reaction", "game", "chat", "team", "friend", "holiday", 
    "winter", "summer", "birthday", "festival", "animal", "ocean", "forest", 
    "planet", "nature", "car", "sports", "bike", "boat", "pirate", "spy", 
    "ninja", "castle", "dragon", "love", "family", "dream", "fun", "sadness", 
    "teamwork", "horror", "mystery", "alien", "future", "time", "space", 
    "war", "drone", "virtual", "smart", "internet", "tool", "gadget", 
    "astronomy", "genetics", "climate", "eco", "score", "level", "boss", 
    "soccer", "tennis", "swim", "fitness", "beat", "dj", "remix", "guitar", 
    "piano", "drum", "sing", "music", "story", "poem", "myth", "culture", 
    "desert", "jungle", "escape", "nano", "mars", "blackhole", "wormhole", 
    "tetris", "snake", "pacman", "retro", "trivia", "memory", "mind", 
    "goal", "self", "psychology", "radio", "news", "trend", "future", 
    "origami", "lego", "block", "challenge", "record", "win", "fear", 
    "adventure", "peace", "curiosity", "train", "plane", "rocket", "ship", 
    "tractor", "startup", "trade", "money", "hide", "tag", "party", "wizard", 
    "spell", "alien", "utopia", "dystopia", "emoji", "monster", "robot", 
    "galaxy", "riddle", "quiz", "superpower", "dreamer", "secret", "garden", 
    "treasure", "map", "adventurer", "alien", "school", "magic", "happiness", 
    "detective", "hunt", "funny", "invention", "discovery", "explorer", 
    "weather", "farming", "spacewalk", "puzzlebox", "memorygame", "sound", 
    "voice", "shadow", "futurecity", "painting", "astronaut", "planet", 
    "energy", "jigsaw", "travel", "fairy", "storybook", "wish", "cloud", 
    "adventurer", "hidden", "forest", "journey", "engineer", "racer", "knight", 
    "battlefield", "rescue", "volcano", "speedway", "supercar", "dino", "craft",
    "ball", "bounce", "bubble", "panda", "fox", "tiger", "kitten", 
    "puppy", "bear", "owl", "penguin", "snow", "ice", "water", 
    "lake", "river", "swim", "beach", "sun", "sky", "starfish", 
    "flower", "tree", "jungle", "mountain", "cave", "dinosaur", 
    "parrot", "butterfly", "ant", "bee", "ladybug", "grass", "rain", 
    "storm", "cloud", "thunder", "lightning", "rainbow", "chocolate", 
    "candy", "cookie", "cake", "fruit", "banana", "apple", "orange", 
    "grape", "pear", "melon", "cherry", "carrot", "pizza", "burger", 
    "popcorn", "icecream", "donut", "chef", "cook", "baker", "fire", 
    "camp", "hike", "forest", "adventurer", "explorer", "fishing", 
    "canoe", "boat", "raft", "whale", "shark", "dolphin", "octopus", 
    "star", "rocketship", "galaxy", "universe", "planet", "meteor", 
    "sunset", "sunrise", "island", "volcano", "lava", "trekking", 
    "climbing", "roller", "slide", "balloon", "kite", "jump", "skate", 
    "snowboard", "sled", "race", "skater", "biker", "scooter", 
    "tunnel", "bridge", "tower", "castle", "palace", "crown", 
    "knight", "princess", "fairy", "wizard", "potion", "magic", 
    "spells", "unicorn", "mermaid", "dragon", "treasure", "coin", 
    "gold", "jewels", "crystal", "pearl", "map", "maze", "trap", 
    "secret", "clue", "detective", "spy", "agent", "mission", 
    "villain", "hero", "rescue", "teamwork", "friendship", "kindness", 
    "gift", "celebrate", "party", "fireworks", "lantern", "festival", 
    "holiday", "snowman", "santa", "reindeer", "elf", "sled", 
    "present", "balloon", "parade", "carnival", "circus", "juggler", 
    "acrobat", "clown", "magician", "musician", "instrument", 
    "drum", "guitar", "violin", "piano", "flute", "sing", "choir", 
    "concert", "song", "lyrics", "story", "poem", "book", "library"
]
"""
QUERY_LIST = ["water", 
    "lake", "river", "swim", "beach", "sun", "sky", "starfish", 
    "flower", "tree", "jungle", "mountain", "cave", "dinosaur", 
    "parrot", "butterfly", "ant", "bee", "ladybug", "grass", "rain", 
    "storm", "cloud", "thunder", "lightning", "rainbow", "chocolate", 
    "candy", "cookie", "cake", "fruit", "banana", "apple", "orange", 
    "grape", "pear", "melon", "cherry", "carrot", "pizza", "burger", 
    "popcorn", "icecream", "donut", "chef", "cook", "baker", "fire", 
    "camp", "hike", "forest", "adventurer", "explorer", "fishing", 
    "canoe", "boat", "raft", "whale", "shark", "dolphin", "octopus", 
    "star", "rocketship", "galaxy", "universe", "planet", "meteor", 
    "sunset", "sunrise", "island", "volcano", "lava", "trekking", 
    "climbing", "roller", "slide", "balloon", "kite", "jump", "skate", 
    "snowboard", "sled", "race", "skater", "biker", "scooter", 
    "tunnel", "bridge", "tower", "castle", "palace", "crown", 
    "knight", "princess", "fairy", "wizard", "potion", "magic", 
    "spells", "unicorn", "mermaid", "dragon", "treasure", "coin", 
    "gold", "jewels", "crystal", "pearl", "map", "maze", "trap", 
    "secret", "clue", "detective", "spy", "agent", "mission", 
    "villain", "hero", "rescue", "teamwork", "friendship", "kindness", 
    "gift", "celebrate", "party", "fireworks", "lantern", "festival", 
    "holiday", "snowman", "santa", "reindeer", "elf", "sled", 
    "present", "balloon", "parade", "carnival", "circus", "juggler", 
    "acrobat", "clown", "magician", "musician", "instrument", 
    "drum", "guitar", "violin", "piano", "flute", "sing", "choir", 
    "concert", "song", "lyrics", "story", "poem", "book", "library"
]